### ISSUE TITLE
Publishing to Go Doesn't Respect the Projen Env Var for GITHUB_REPO

### ISSUE THREAD

**Issue by hakenmt** [cdklabs/publib#1325]
Using a projen configuration like this:

```
publishToGo: {
    moduleName: 'example.com/modulename',
    packageName: 'modulename',
    githubRepo: 'github.com/my-org/modulename',
  },
```

It sets the release workflow like this:

```
- name: Release
        env:
          GITHUB_REPO: github.com/my-org/modulename
          GIT_USER_NAME: github-actions
          GIT_USER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GO_GITHUB_TOKEN }}
        run: npx -p publib@latest publib-golang
```

But I can't see where in this library the `GITHUB_REPO` environment variable is ever used. It looks like in `go.ts`, https://github.com/cdklabs/publib/blob/971a5059497a04223b7e33816d143d0b7c1975d6/src/targets/go.ts#L228 that the library only ever parses the module name and checks that against matching `github.com`, meaning you can't use a custom domain name for the module name and specify the github repo as something different.
