### ISSUE TITLE
Support publishing maven packages to AWS CodeArtifact

### ISSUE THREAD

**Issue by cj-taylor** [cdklabs/publib#265]
I believe the existing implementation can be extended to conditionally handle AWS CodeArtifact and use AWS CLI, like the NPM implementation, to get the AWS CodeArtifact temporary authorization token for use as `MAVEN_PASSWORD`.

I traced an issue I was having in projen (v0.43.0) back to this project. When attempting to build an AWS Construct Library published to AWS CodeArtifact to both NPM and Maven, only NPM was supported. I was unable to get Maven to function and thought it best to dig deeper to bring first-class support forward.

GitHub Packages support (#11, #12) provides a great foundation to extend to fully address AWS CodeArtifact support (#10)

Once implemented, an example GitHub Actions publish step could look like:

```yaml
- name: Publish package
  run: npx -p jsii-release jsii-release-maven
  env:
    MAVEN_SERVER_ID: codeartifact
    MAVEN_USERNAME: ${{ github.actor }}
    MAVEN_REPOSITORY_URL: "https://my_domain-111122223333.d.codeartifact.us-west-2.amazonaws.com/maven/my_repo/'"
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

We could borrow from the NPM implementation (https://github.com/cdklabs/jsii-release/blob/master/bin/jsii-release-npm#L23-L38) to conditionally assign environment variable `MAVEN_PASSWORD` to an AWS CodeArtifact authorization token using AWS CLI if the `MAVEN_REPOSITORY_URL` is defined and matches an AWS CodeArtifact pattern. This then would be picked up by `\${env.MAVEN_USERNAME}` within `mvn-settings.xml` creation steps.
